### ISSUE TITLE
Kolejne kroki

### ISSUE THREAD

**Issue by Nowosad** [bananaonthemoon/wybory#1]
- [x] - przygotowanie kodu do czyszczenia danych i danych

**Comment by Nowosad** [comment]
Dalej jest problem z brakiem jednej jednostki? W którym pliku i linii mogę to zobaczyć?

**Comment by bananaonthemoon** [comment]
powstaje to podczas upraszczania (linia 73), kombinuję z keep, ale wszystko tak strasznie długo się ładuje, że nie wyobrażam sobie etapu wizualizacji na ten moment. chyba będę próbować jeszcze na wzór https://gis.stackexchange.com/questions/62292/how-to-speed-up-the-plotting-of-polygons-in-r

**Comment by bananaonthemoon** [comment]
Dobra, chyba już wiem gdzie może być błąd. W międzyczasie zielona góra wchłonęła większość gmin wokół siebie i to może być źródło problemów.

**Comment by Nowosad** [comment]
:+1:

**Comment by bananaonthemoon** [comment]
Udało mi się skrócić ładowanie, ustawiłam keep = 0.1 i method = "vis" zamiast douglasa-peukera i jest znośnie. Trochę nieładnie wygląda wczytywanie shp, upraszczanie, zapisywanie jako gpkg i wczytywanie go, ale jednak coś za coś.
