### ISSUE TITLE
Poźniejsze pomysły

### ISSUE THREAD

**Issue by Nowosad** [bananaonthemoon/wybory#2]
- [ ] - analiza w wielu skalach
- [ ] - może rozdział z animacjami (e.g., https://flowingdata.com/2019/10/08/fixing-the-impeach-this-map-with-a-transition-to-a-cartogram/)

**Comment by bananaonthemoon** [comment]
https://neocarto.github.io/mapextrud/vignettes/how-to-build-extruded-maps.html
lub 
![EXvFaI5WoAY2DKA](https://user-images.githubusercontent.com/61518849/81803949-ab111a80-9518-11ea-9c28-28f84b858e73.png)

**Comment by bananaonthemoon** [comment]
chciałabym się spytać, czy dodawanie do puli map takich przykładów miałoby sens? tylko nie wiem czy wtedy taktować środkową wartość jako 0 czy jednak jakieś wartości powinny się tam znaleźć
![woj_regplot_roznica](https://user-images.githubusercontent.com/61518849/100228491-0e95ef00-2f23-11eb-91cd-41597a6d7632.png)
![pow_rawplot_roznica](https://user-images.githubusercontent.com/61518849/100228521-1a81b100-2f23-11eb-9afd-5dea22f59be1.png)
