### ISSUE TITLE
Kolejne kroki

### ISSUE THREAD

**Issue by Nowosad** [bananaonthemoon/wybory#4]
- [x] - dodanie stworzonych plików do repozytorium
- [x] - testowanie wizualizacji używając **geogrid** i **cartogram** dla województw i mniejszych jednostek (zmienna frekwencja w %)

**Comment by bananaonthemoon** [comment]
w sprawie różnych jednostek: zrobić 3 osobne kody+gpkg dla gmin, powiatów i województw czy lepiej byłoby agregować je po kolei w jednym w pliku z kodem?

**Comment by Nowosad** [comment]
Myślę, że nie to dużej różnicy. Ja bym na Pani miejscu napisał trzy skrypty.

**Comment by bananaonthemoon** [comment]
Właśnie tak robię, ale wolałam się upewnić. Dziękuję :)
