### ISSUE TITLE
viz: markdown

### ISSUE THREAD

**Issue by bananaonthemoon** [bananaonthemoon/wybory#6]
@Nowosad, przy uruchamianiu pierwszego chunka pojawia się error "Error: Fill argument neither colors nor valid variable name(s)".  Wyskakuje on na samym końcu, przy tmap_arrange.  Przecież nawet nie używam argumentu fill?

**Comment by Nowosad** [comment]
@bananaonthemoon proszę dodać tutaj powtarzalny przykład

**Comment by bananaonthemoon** [comment]
Jest w repo https://github.com/bananaonthemoon/wybory/blob/master/kod/viz_markdown.Rmd (o takie coś chodzi, si?)

**Comment by Nowosad** [comment]
Blisko. Najlepiej byłoby użyć pakietu reprex do tego:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(tmap)
prez = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez, stringsAsFactors=FALSE) 
prez_woj$Nazwa4 = substr(prez_woj$Nazwa, 1, 4)
# rawplot -----------------------------------------------------------------
rawplot_woj = tm_shape(prez_woj) + 
  tm_polygons("t1.duda", palette = "viridis") +
  tm_text("Nazwa4")
rawplot_woj
#> Error: Fill argument neither colors nor valid variable name(s)
```

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Nowosad** [comment]
Problem - nie ma w danych kolumny `t1.duda`. Jest za to `f1.duda`:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(tmap)
prez = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez, stringsAsFactors=FALSE) 
prez_woj$Nazwa4 = substr(prez_woj$Nazwa, 1, 4)
# rawplot -----------------------------------------------------------------
rawplot_woj = tm_shape(prez_woj) + 
  tm_polygons("f1.duda", palette = "viridis") +
  tm_text("Nazwa4")
rawplot_woj
```

![](https://i.imgur.com/n9oOsSi.png)

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bananaonthemoon** [comment]
Przepraszam za kłopot, myślałam że wszędzie już poprawiłam :(

**Comment by Nowosad** [comment]
No problem.
