### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by bananaonthemoon** [bananaonthemoon/wybory#7]
- [x] dokończyć r markdown:
- [x] geogrid
- [x] poprawić _woj w powiatach
- [ ] cartogram
- [ ] dodać granice polski/województw do cartogram
- [ ] linemap
- [x] wybrać palety kolorystyczne (to chciałabym obgadać z kimś ze społ-ekon, bo miałam zawsze wpajane, że byle kolorów też nie powinno się wstawiać bo ładnie wygląda? może to się zmienia z nowym pokoleniem)
- [ ] mapdeck
- [ ] tmap_save() jak coś
- [ ] posprawdzać przedziały dopiero potem liczbę klas
- [ ] legend.only
- [ ] https://github.com/neocarto/mapextrud

**Comment by Nowosad** [comment]
- [ ] rayshader - https://github.com/tylermorganwall/rayshader

**Comment by bananaonthemoon** [comment]
co trzeba było zrobić, żeby palety kolorów się nie wyświetlały w markdownie?

**Comment by Nowosad** [comment]
@bananaonthemoon Pani Mario, proszę mi przygotować mały plik .Rmd z problemem.

**Comment by bananaonthemoon** [comment]
https://github.com/bananaonthemoon/wybory/blob/master/plik_mk1.Rmd

w międzyczasie znalazłam jeszcze taki błąd? najlepsze jest to, że w starszych plikach (np. z wtorku) tego problemu nie ma i liczy normalnie
https://github.com/bananaonthemoon/wybory/blob/master/plik_mk2.Rmd

**Comment by Nowosad** [comment]
1:
```r
paleta_blue = get_brewer_pal("Blues", plot = FALSE)
```
2:
proszę o przesłanie wyniku funkcji `sessionInfo()` oraz informacji jakie wersje GDAL i PROJ się wyświetlają jak uruchomi Pani `library(sf)` w czystej sesji R

**Comment by bananaonthemoon** [comment]
```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250   
[3] LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                  
[5] LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.0  htmltools_0.4.0 tools_4.0.0     yaml_2.2.1     
 [5] Rcpp_1.0.4.6    rmarkdown_2.1   knitr_1.28      xfun_0.13      
 [9] digest_0.6.25   rlang_0.4.5     evaluate_0.14 
```
```
Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
```

**Comment by Nowosad** [comment]
Okej,
ma Pani pakiet sf w wersji 0.9-2, prawda?

**Comment by bananaonthemoon** [comment]
O.O a no, już aktualizuję!

**Comment by Nowosad** [comment]
Proszę od tego zacząć. Ogólnie wersja 0.9-0 wprowadziła duże zmiany dla wszystkich użytkowników, a następnie wersja 0.9-3 zrobiła dużą aktualizację dla Windowsa (ta wersja chyba jeszcze nie jest dostępna do zainstalowania, ale będzie w ciągu kilku dni)

**Comment by bananaonthemoon** [comment]
no właśnie ciągle mi reinstaluje 0.9-2. po weekendzie najwyżej wrócę do tego. pytanie tylko czemu w starszych plikach wszystko działało?

**Comment by Nowosad** [comment]
https://www.youtube.com/watch?v=Va0STgco7-4 - od 14:27 do 27:48

**Comment by bananaonthemoon** [comment]
Kod dla geogrid etc. powinien odpowiadać temu co jest w markdownie, czy wystarczy np. jedna zmienna dla województwa?

**Comment by Nowosad** [comment]
Chyba nie rozumiem pytania. 
Ale w kwestii **geogrid** to sugerowałbym poeksperymentować z różnymi ustawieniami gridów, wybrać najlepsze ustawienie dla województw, powiatów, itd., następnie zapisać najlepsze ustawienia do plików, a w raportach tylko wczytywać najlepsze ustawienie.

**Comment by bananaonthemoon** [comment]
na chwilę obecną przy eksperymentowaniu tworzę wersję robocze .rmd w osobnych folderach (tak, abym potem mogła je sobie porównać) a oryginalne pliki .r zostawiam w spokoju i tylko na poziomie województw... mały bajzel jest.

**Comment by bananaonthemoon** [comment]
sformatowałam dyski i zainstalowałam wszystko od nowa, sf jest w wersji 0.9-3, ale dalej wyskakuje ```common_crs(x, y)': coordinate reference systems not equal: use st_transform() first?```
wersje gdal i proj ```linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1```

**Comment by Nowosad** [comment]
@bananaonthemoon mam prawie te same wersje bibliotek i kod działa bez problemu.
Może spróbować Pani zmienić `cache` na `FALSE`? Jak to nie pomoże to proszę o numery wersji **sf** i **cartogram**

**Comment by bananaonthemoon** [comment]
zmieniłam cache na false i dalej wyskakuje błąd. cartogram 0.2.0 a sf 0.9-3

**Comment by bananaonthemoon** [comment]
szkoda, że ta funkcja szwankuje u mnie, może nie mam czegoś zainstalowanego? i tak jeszcze mam do ogarnięcia linemap i rayshader

**Comment by Nowosad** [comment]
Pani Mario, to debugujemy dalej:

1. Proszę wyizolować jeszcze mniejszy kawałek kodu z błędem (pakiety, wczytanie danych, obliczenia, błąd)
2. Proszę też spróbować użyć wersji tych pakietów z githuba

**Comment by bananaonthemoon** [comment]
```
library(tidyverse)
devtools::install_github("sjewo/cartogram")
library(cartogram)
devtools::install_github("r-spatial/sf")
library(sf)

prez_w = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez_w, stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180)

prez_woj_ncont_duda = cartogram_ncont(prez_woj, "t1.duda")
```
i dalej błąd.  
```
Błąd w poleceniu 'common_crs(x, y)':
  coordinate reference systems not equal: use st_transform() first?
```

**Comment by bananaonthemoon** [comment]
!!!! https://github.com/r-spatial/sf/issues/798

**Comment by Nowosad** [comment]
`remotes::install_github("tidyverse/dplyr")` + restart R + test

**Comment by bananaonthemoon** [comment]
d z i a ł a !

**Comment by bananaonthemoon** [comment]
podejrzewam, że tych poligonów jest po prostu za dużo i dlatego tak wychodzi?
![image](https://user-images.githubusercontent.com/61518849/82043173-62d63180-96ab-11ea-9e11-1d42f86afd7b.png)

**Comment by bananaonthemoon** [comment]
nie byłam pewna, czy na mejla wysłać czy tutaj lepiej wrzucić, ale dodałam zarys https://github.com/bananaonthemoon/wybory/blob/master/zarys.Rmd @Nowosad

**Comment by bananaonthemoon** [comment]
wygląda na to, że tamto czyszczenie danych było w większości na marne... https://wybory.gov.pl/prezydent20200628/pl/dane_w_arkuszach

**Comment by bananaonthemoon** [comment]
to całe czyszczenie danych było bez większego sensu... https://wybory.gov.pl/prezydent20200628/pl/dane_w_arkuszach :(

**Comment by Nowosad** [comment]
Dlaczego? Jest teraz inna struktura?

[Nawiasem mówiąc, na pewno nie było bez sensu, bo się Pani nauczyła dane czyścić]

**Comment by bananaonthemoon** [comment]
Jest już podział na jednostki + frekwencja oraz wyniki w procentach. Wcześniej były tylko dane dla okręgów wyborczych. No dobrze, może nie całkowicie bez sensu :) ale trzeba będzie wyrzucić z połowę kodu przy gminach

**Comment by bananaonthemoon** [comment]
jest uno problemo: poczas uruchamiania https://github.com/bananaonthemoon/wybory/blob/master/rmarkdown/rmark_cartogram.Rmd w linii 31 pojawia się błąd: 
```Błąd w poleceniu 'CPL_geos_op("buffer", x, dist, nQ, numeric(0), logical(0))':
Evaluation error: IllegalArgumentException: Points of LinearRing do not form a closed linestring.
Wywołania: <Anonymous> ... st_buffer -> st_buffer.sfc -> st_sfc -> CPL_geos_op
Wykonywanie wstrzymane
```
ale niby wszystko jest ok z geometrią?

**Comment by Nowosad** [comment]
Jak wygląda wynik działania funkcji `st_is_valid()` na wejściowych danych?

**Comment by bananaonthemoon** [comment]
same ```true```

**Comment by Nowosad** [comment]
@bananaonthemoon mam teraz małe problemy z moim komputerem do obliczeń. Czy może Pani przygotować i wrzucić tutaj reprex?

**Comment by bananaonthemoon** [comment]
```
library(cartogram)
library(tmap)
library(maptools)
#> Ładowanie wymaganego pakietu: sp
#> Checking rgeos availability: TRUE
library(dplyr)
#> 
#> Dołączanie pakietu: 'dplyr'
#> Następujące obiekty zostały zakryte z 'package:stats':
#> 
#>     filter, lag
#> Następujące obiekty zostały zakryte z 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(tmaptools)

prez_w = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg"
prez_woj = read_sf(prez_w, stringsAsFactors=FALSE) %>%
  st_transform(crs = 2180)

st_is_valid(prez_woj)
#>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
#> [16] TRUE

# Continuous Area Cartogram
prez_woj_cont_duda = cartogram_cont(prez_woj, "t1_Andrzej.Sebastian.DUDA", 8)
#> Mean size error for iteration 1: 1.40827379474522
#> Mean size error for iteration 2: 1.22526299243185
#> Mean size error for iteration 3: 1.12846581000214
#> Mean size error for iteration 4: 1.07451122846902
#> Mean size error for iteration 5: 1.04364204239174
#> Mean size error for iteration 6: 1.02596073019451
#> Mean size error for iteration 7: 1.01567851305779
#> Mean size error for iteration 8: 1.00948110939182
prez_woj_cont_frek = cartogram_cont(prez_woj, "t1_Frekwencja", 50, threshold = 0.1)
#> Mean size error for iteration 1: 1
#> Error in CPL_geos_op("buffer", x, dist, nQ, numeric(0), logical(0)): Evaluation error: IllegalArgumentException: Points of LinearRing do not form a closed linestring.
```

**Comment by Nowosad** [comment]
`prez_woj` to POLYGON czy MULTIPOLYGON?

**Comment by bananaonthemoon** [comment]
polygon

**Comment by Nowosad** [comment]
Ciekawe - na moim laptopie nie mam tego błędu. Jaką ma Pani wersję pakietu cartogram? Czy próbowała Pani pobrać najnowszą wersję z githuba?

**Comment by bananaonthemoon** [comment]
```Skipping install of cartogram from a github remote, the SHA1 (224876b1) has not changed since last install.

**Comment by bananaonthemoon** [comment]
Uaktualniłam też pakiety

**Comment by bananaonthemoon** [comment]
chyba odinstaluję i zainstaluję wszystko...

**Comment by Nowosad** [comment]
Ja mam wersję 0.2.0 cartogram oraz 0.9-5 sf.

**Comment by bananaonthemoon** [comment]
Też mam takie same wersje. Wcześniej ten błąd się jednak nie pojawiał :(

**Comment by bananaonthemoon** [comment]
OJEZUUU. zrobiłam od nowa .gpkg i wrzuciłam na githuba, przeszło! mimo, że dzisiaj już dobre 3 razy go wrzucałam...? anyways, nowy błąd (linia niżej... przy cartogram_ncont) 
```BŁĄD: Assigned data `*vtmp*` must be compatible with existing data. i Error occurred for column `geom`. x Can't convert <sfc_POLYGON> to <sfc_POLYGON>. x Some attributes are incompatible. i The author of the class should implement vctrs methods. i See <https://vctrs.r-lib.org/reference/faq-error-incompatible-attributes.html>.```

**Comment by Nowosad** [comment]
Ten error chyba już widziałem z dwa tygodnie temu, ale nie miałem czasu go zgłosić. Niech Pani przygotuje reprex i zgłosi ten błąd na https://github.com/sjewo/cartogram/issues.

**Comment by bananaonthemoon** [comment]
Done i done

**Comment by bananaonthemoon** [comment]
Może trochę głupie pytanie, ale jak połączyć datatable ze współrzędnymi z geopackage jeśli nie mają wspólnej kolumny?

reprex:
```
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

woj = "https://raw.github.com/bananaonthemoon/wybory/master/dane/prez_woj.gpkg" %>%
  read_sf() %>%
  st_transform(crs = 4326)

woj_longlat = st_coordinates(st_centroid(woj))
#> Warning in st_centroid.sf(woj): st_centroid assumes attributes are constant over
#> geometries of x
#> Warning in st_centroid.sfc(st_geometry(x), of_largest_polygon =
#> of_largest_polygon): st_centroid does not give correct centroids for longitude/
#> latitude data
```

**Comment by Nowosad** [comment]
Mogę prosić o dokładniejszy opis problemu?

**Comment by bananaonthemoon** [comment]
W pakiecie `mapdeck` potrzebne są osobne kolumny z szerokością i długością geograficzną, ja w .gpkg mam tylko w formie geom. No więc kombinuję, ale jedyne co udało mi się zrobić to osobny dataframe z long i lat, ale nie mam możliwości połączenia .gpkg z df.

**Comment by Nowosad** [comment]
@bananaonthemoon mapdeck nie potrzebuje tych kolumn, jeżeli w argumencie data jest obiekt klasy sf. 
(btw: myślę, że lepiej na przyszłość otwierać (i zamykać) nowe issue na githubie z nowymi pytaniami)

**Comment by bananaonthemoon** [comment]
Aaaa, ja się głównie opieram na https://symbolixau.github.io/mapdeck/articles/mapdeck.html i nie zauważyłam. Dziękuję!
